li = input().split()
sum = int(li[0]) + int(li[1])
dis = int(li[0]) - int(li[1])
pro = int(li[0]) * int(li[1])
re = int(li[0]) // int(li[1])
mod = int(li[0]) % int(li[1])
print(sum)
print(dis)
print(pro)
print(re)
print(mod)